# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            IDEP Partner Toolkit
tagline:          'UCLA'
description:      'A guide to standards and workflows for IDEP partner institutions.'
url:
baseurl:          /ideptoolkit/

author:
  name:           'Dawn Childress'
  url:

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/uclalibrary/ideptoolkit

defaultlang:      eng

t:
  English:
    title:        'IDEP Partners Toolkit'
    description:  'A guide to standards and workflows for IDEP partner institutions.'
  Español:
    title:        ''
    description:  'Una guía de estándares y flujos de trabajo para las instituciones asociadas al IDEP.'
    home:   spa
  հայերեն:
    title:        ''
    description:  'IDEP գործընկեր հաստատությունների համար ստանդարտների եւ աշխատանքի արդյունքի ուղեցույց:'
    home:   arm
  عربى:
    title:        ''
    description:  'دليل إرشادي للمشروع الدولي لرقمنة المطبوعات العابرة'
    home:   ara
